# Daily CI job to run tests with isolation mode enabled by default

name: test-isolate

permissions: {}

on:
  workflow_dispatch: # Needed so we can run it manually

jobs:
  nextest:
    uses: ./.github/workflows/nextest.yml
    permissions:
      contents: read
    with:
      profile: isolate